default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: aziz_development

test:
  <<: *default
  database: aziz_test

production:
  <<: *default
  database: aziz_production
  username: aziz
  password: <%= ENV['aziz_DATABASE_PASSWORD'] %>

external_db:
  adapter: sqlserver
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  host:     <%= ENV['DATABASE_HOSTNAME'] %>